#fill out client config and copy this file. Rename the copy to settings.yaml

client_config_backend: settings
client_config:
  client_id: <Your google client id here>
  client_secret: <Your google client secret here>

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope: 
- https://www.googleapis.com/auth/drive.file